<?php

namespace Linotype\Core\Model;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class BlockModel implements ConfigurationInterface
{

    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder('block');
        $rootNode = $treeBuilder->getRootNode();
        $rootNode
            ->children()
                ->floatNode('version')
                    ->defaultValue(1.0)
                    ->info('')
                    ->end()
                ->scalarNode('author')
                    ->defaultValue('Unknow')
                    ->info('')
                    ->end()
                ->scalarNode('name')
                    ->defaultValue('Unknow')
                    ->info('')
                    ->end()
                ->scalarNode('desc')
                    ->defaultValue('')
                    ->info('')
                    ->end()
                ->arrayNode('package')
                    ->defaultValue([])
                    ->scalarPrototype()->end()
                    ->info('')
                    ->end()
                ->arrayNode('parent')
                    ->defaultValue(['all'])
                    ->beforeNormalization()->castToArray()->end()
                    ->scalarPrototype()->end()
                    ->info('')
                    ->end()
                ->arrayNode('accept')
                    ->defaultValue(['all'])
                    ->beforeNormalization()->castToArray()->end()
                    ->scalarPrototype()->end()
                    ->info('')
                    ->end()
                ->variableNode('role')
                    ->defaultValue('default')
                    ->info('')
                    ->end() 
                ->arrayNode('context')
                    ->arrayPrototype()
                    ->children()
                        ->scalarNode('name')
                            ->defaultValue('Unknow')
                            ->info('')
                            ->end()
                        ->scalarNode('desc')
                            ->defaultValue('')
                            ->info('')
                            ->end()
                        ->scalarNode('field')
                            ->defaultValue('Text')
                            ->info('')
                            ->end()
                        ->variableNode('option')
                            ->defaultValue([])
                            ->info('')
                            ->end()
                        ->enumNode('persist')
                            ->values(['static', 'meta', 'option','both'])
                            ->defaultValue('static')
                            ->info('')
                            ->end()
                        ->variableNode('role')
                            ->defaultValue('default')
                            ->info('')
                            ->end()    
                        ->variableNode('value')
                            ->defaultValue('')
                            ->info('')
                            ->end()
                        ->variableNode('default')
                            ->defaultValue('')
                            ->info('')
                            ->end()
                        ->variableNode('preview')
                            ->defaultValue('')
                            ->info('')
                            ->end()
                        ->variableNode('format')
                            ->defaultValue('')
                            ->info('')
                            ->end()
                        ->booleanNode('debug')
                            ->defaultFalse()
                            ->info('')
                            ->end()
                        ->booleanNode('js')
                            ->defaultFalse()
                            ->info('')
                            ->end()
                        ->booleanNode('css')
                            ->defaultFalse()
                            ->info('')
                            ->end()
                        ->end()
                    ->end()
                    ->info('')
                    ->end()
            ->end()
        ;
        return $treeBuilder;
    }
    
}
